services:
  bb_nginx_dev:
    container_name: bb_nginx_dev
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/dev/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/logs:/var/log/nginx # nginx logs
      - ./docker/nginx/ssl:/etc/letsencrypt:ro
      # - certificates:/etc/letsencrypt/live
    expose:
      - 44301
    networks:
      - internal-zeebra
      - nginx-proxy

  bb_bot_dev:
    container_name: bb_bot_dev
    restart: always
    build:
      context: .
      dockerfile: ./docker/zeebra_bot/Dockerfile
    env_file:
      - docker/zeebra_bot/.dev.env
    volumes:
      - ./reels:/app/reels
      - ./logs:/app/logs
      - ./saved_images:/app/saved_images
    expose:
      - 5000
    depends_on:
      - bb_db_dev
    networks:
      - internal-zeebra

  bb_db_dev:
    container_name: bb_db_dev
    restart: always
    image: postgres:15
    shm_size: 128mb
    env_file:
      - docker/db/.dev.env
    volumes:
      - bb_db_data_dev:/var/lib/postgresql/data
      - ./docker/db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    expose:
      - 5432
    networks:
      - internal-zeebra

  bb_website_dev:
    container_name: bb_website_dev
    restart: always
    build:
      context: .
      dockerfile: ./docker/website/DockerfileDev
    env_file:
      - docker/website/.dev.env
    expose:
      - 8080
    networks:
      - internal-zeebra

  bb_adminer_dev:
    container_name: bb_adminer_dev
    image: adminer
    restart: always
    expose:
      - 8080
    networks:
      - internal-zeebra

volumes:
  bb_db_data_dev:

networks:
  internal-zeebra:
    driver: bridge
  nginx-proxy:
    external: true
